#compose.yaml
version: '3.8'
services:
  app:
    build: 
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    command: ["./venv/bin/python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080"]