# docker-compose.yaml
version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: ["./venv/bin/python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080"]